export enum StyleClasses {
     SLIDER = "simpleslider",
     SLIDERV = "simpleslider_vertical",
     WRAPPER = "simpleslider__wrapper",
     WRAPPERV = "simpleslider__wrapper_vertical",
     LINE = "simpleslider__line",
     LINEV = "simpleslider__line_vertical",
     HANDLE = "simpleslider__handle",
     HANDLEV = "simpleslider__handle_vertical",
     HEADER = "simpleslider__header",
     RANGE = "simpleslider__range",
     RANGEV = "simpleslider__range_vertical",
     CURRENTVAL = "simpleslider__current-value",
     CURRENTVALV = "simpleslider__current-value_vertical",
     CURRENTVALWRAPPER = "simpleslider__current-value-wrapper",
     CURRENTVALWRAPPERV = "simpleslider__current-value-wrapper_vertical",
     CURRENTVALTEXT = "simpleslider__current-value-text",
     CURRENTVALARROW = "simpleslider__current-value-arrow",
     CURRENTVALARROWV = "simpleslider__current-value-arrow_vertical",
     MAINWRAPPER = "simpleslider__main-wrapper",
     MAINWRAPPERV = "simpleslider__main-wrapper_vertical",
     HANDLEWRAPPER = "simpleslider__handle-wrapper",
     HANDLEWRAPPERV = "simpleslider__handle-wrapper_vertical",
}